rule all_exomeseq_somatic:
    input:  expand("{s}"+".realign.bam",s=samples),
            expand("mutect2_out/{p}"+".FINAL.vcf",p=pairs),
            expand("mutect_out/{p}"+".FINAL.vcf",p=pairs),
            expand("strelka_out/{p}"+".vcf",p=pairs),
            expand("mutect2_out/oncotator_out/{p}"+".maf",p=pairs),
            expand("strelka_out/oncotator_out/{p}"+".maf",p=pairs),
            expand("mutect_out/oncotator_out/{p}"+".maf",p=pairs),
            "strelka_out",
            "mutect2_out",
            "cnvkit_out",
            "mutect_out",
            "delly_out",
            "germline_snps.vcf",
#            expand("cnvkit_out/{p}"[1]+".cnr",
#            expand("cnvkit_out/{p}"[1]+".cns",
#            expand("delly_out/{p}"[1]+"del.bcf",
#            expand("delly_out/{p}"[1]+"ins.bcf",
#            expand("delly_out/{p}"[1]+"dup.bcf",
#            expand("delly_out/{p}"[1]+"tra.bcf",
#            expand("delly_out/{p}"[1]+"inv.bcf",
            "mutect2_out/merged_somatic.vcf",
            "mutect2_out/merged_somatic_snpEff.vcf",
            "variants.bed",
            "full_annot.txt.zip",
            "sample_network.bmp",
            "variants.database",
            "mutect2_out/oncotator_out/mutect2_variants.maf",
            "mutect2_out/mutsigCV_out/somatic.sig_genes.txt",
            "strelka_out/oncotator_out/strelka_variants.maf",
            "strelka_out/mutsigCV_out/somatic.sig_genes.txt",
            "mutect_out/oncotator_out/mutect_variants.maf",
            "mutect_out/mutsigCV_out/somatic.sig_genes.txt"

    output:
